# weapons_compatibility_data.py
# AUTO-GENERATED. DO NOT EDIT MANUALLY.

WEAPON_COMPATIBILITY = {   'GTB Athena': {   'primary': {   'Avenger',
                                     'Disruptor',
                                     'Flail',
                                     'Leech Cannon',
                                     'ML-16 Laser',
                                     'S-Breaker',
                                     'VLL-9 Laser'},
                      'secondary': {   'Barracuda',
                                       'Cluster Bomb',
                                       'D-Missile',
                                       'EM Pulse',
                                       'Fang',
                                       'Fury',
                                       'Havoc',
                                       'Hornet',
                                       'Hornet#Weak',
                                       'Interceptor',
                                       'Interceptor#Weak',
                                       'Phoenix V',
                                       'Stiletto',
                                       'Synaptic'}},
    'GTB Medusa': {   'primary': {   'Avenger',
                                     'Leech Cannon',
                                     'ML-16 Laser',
                                     'Prometheus',
                                     'Prometheus A',
                                     'Prometheus R',
                                     'Railgun',
                                     'S-Breaker',
                                     'VLL-9 Laser'},
                      'secondary': {   'Barracuda',
                                       'Cluster Bomb',
                                       'EM Pulse',
                                       'Havoc',
                                       'Hornet',
                                       'Hornet#Weak',
                                       'MX-50',
                                       'Phoenix V',
                                       'Serkr',
                                       'Serkr#short',
                                       'Stiletto',
                                       'Synaptic',
                                       'Tsunami'}},
    'GTB Ursa': {   'primary': {   'Akheton SDG',
                                   'Avenger',
                                   'Disruptor',
                                   'Flail',
                                   'Leech Cannon',
                                   'ML-16 Laser',
                                   'Prometheus',
                                   'Prometheus A',
                                   'Prometheus R',
                                   'Railgun',
                                   'S-Breaker',
                                   'UD-1 Volz',
                                   'VLL-9 Laser'},
                    'secondary': {   'Barracuda',
                                     'Cluster Bomb',
                                     'D-Missile',
                                     'EM Pulse',
                                     'Fang',
                                     'Fury',
                                     'Harbinger',
                                     'Havoc',
                                     'Hornet',
                                     'Hornet#Weak',
                                     'Interceptor',
                                     'Interceptor#Weak',
                                     'MX-50',
                                     'Phoenix V',
                                     'Serkr',
                                     'Serkr#short',
                                     'Stiletto',
                                     'Synaptic',
                                     'Tsunami'}},
    'GTB Zeus': {   'primary': {   'Akheton SDG',
                                   'Avenger',
                                   'Disruptor',
                                   'Flail',
                                   'Leech Cannon',
                                   'ML-16 Laser',
                                   'Prometheus',
                                   'Prometheus A',
                                   'Prometheus R',
                                   'Railgun',
                                   'S-Breaker',
                                   'UD-1 Volz',
                                   'VLL-9 Laser'},
                    'secondary': {   'Barracuda',
                                     'Cluster Bomb',
                                     'D-Missile',
                                     'EM Pulse',
                                     'Fang',
                                     'Fury',
                                     'Havoc',
                                     'Hornet',
                                     'Hornet#Weak',
                                     'Interceptor',
                                     'Interceptor#Weak',
                                     'Phoenix V',
                                     'Stiletto',
                                     'Synaptic',
                                     'Tsunami'}},
    'GTDr Amazon': {'primary': {'Training'}, 'secondary': set()},
    'GTF Angel': {   'primary': {   'Avenger',
                                    'Disruptor',
                                    'ML-16 Laser',
                                    'Prometheus',
                                    'Prometheus A',
                                    'Prometheus R',
                                    'VLL-9 Laser'},
                     'secondary': {   'Fang',
                                      'Fury',
                                      'Hornet',
                                      'Hornet#Weak',
                                      'Interceptor',
                                      'Interceptor#Weak',
                                      'MX-50'}},
    'GTF Apollo': {   'primary': {   'Avenger',
                                     'Disruptor',
                                     'Flail',
                                     'Leech Cannon',
                                     'ML-16 Laser',
                                     'Prometheus',
                                     'Prometheus A',
                                     'Prometheus R',
                                     'S-Breaker',
                                     'VLL-9 Laser'},
                      'secondary': {   'Cluster Bomb',
                                       'D-Missile',
                                       'EM Pulse',
                                       'Fang',
                                       'Fury',
                                       'Hornet',
                                       'Hornet#Weak',
                                       'Interceptor',
                                       'Interceptor#Weak',
                                       'MX-50'}},
    'GTF Hercules': {   'primary': {   'Akheton SDG',
                                       'Avenger',
                                       'Banshee',
                                       'Disruptor',
                                       'Flail',
                                       'Leech Cannon',
                                       'ML-16 Laser',
                                       'Prometheus',
                                       'Prometheus A',
                                       'Prometheus R',
                                       'Railgun',
                                       'S-Breaker',
                                       'UD-1 Volz',
                                       'VLL-9 Laser'},
                        'secondary': {   'Cluster Bomb',
                                         'D-Missile',
                                         'EM Pulse',
                                         'Fang',
                                         'Fury',
                                         'Havoc',
                                         'Hornet',
                                         'Hornet#Weak',
                                         'Interceptor',
                                         'Interceptor#Weak',
                                         'MX-50',
                                         'Phoenix V'}},
    'GTF Loki': {   'primary': {   'Akheton SDG',
                                   'Avenger',
                                   'Banshee',
                                   'Disruptor',
                                   'Flail',
                                   'Leech Cannon',
                                   'ML-16 Laser',
                                   'Prometheus',
                                   'Prometheus A',
                                   'Prometheus R',
                                   'Railgun',
                                   'UD-1 Volz',
                                   'VLL-9 Laser'},
                    'secondary': {   'D-Missile',
                                     'EM Pulse',
                                     'Fang',
                                     'Fury',
                                     'Hornet',
                                     'Hornet#Weak',
                                     'Interceptor',
                                     'Interceptor#Weak',
                                     'MX-50',
                                     'Phoenix V'}},
    'GTF Loki#stealth': {   'primary': {   'Akheton SDG',
                                           'Avenger',
                                           'Banshee',
                                           'Disruptor',
                                           'Flail',
                                           'Leech Cannon',
                                           'ML-16 Laser',
                                           'Prometheus',
                                           'Prometheus A',
                                           'Prometheus R',
                                           'Railgun',
                                           'UD-1 Volz',
                                           'VLL-9 Laser'},
                            'secondary': {   'D-Missile',
                                             'EM Pulse',
                                             'Fang',
                                             'Fury',
                                             'Hornet',
                                             'Hornet#Weak',
                                             'Interceptor',
                                             'Interceptor#Weak',
                                             'MX-50',
                                             'Phoenix V'}},
    'GTF Ulysses': {   'primary': {   'Akheton SDG',
                                      'Avenger',
                                      'D-Advanced',
                                      'Disruptor',
                                      'Flail',
                                      'Leech Cannon',
                                      'ML-16 Laser',
                                      'Prometheus',
                                      'Prometheus A',
                                      'Prometheus R',
                                      'Railgun',
                                      'S-Breaker',
                                      'UD-1 Volz',
                                      'VLL-9 Laser'},
                       'secondary': {   'D-Missile',
                                        'EM Pulse',
                                        'Fang',
                                        'Fury',
                                        'Hornet',
                                        'Hornet#Weak',
                                        'Interceptor',
                                        'Interceptor#Weak',
                                        'MX-50'}},
    'GTF Valkyrie': {   'primary': {   'Avenger',
                                       'Banshee',
                                       'Disruptor',
                                       'Leech Cannon',
                                       'ML-16 Laser',
                                       'Prometheus',
                                       'Prometheus A',
                                       'Prometheus R',
                                       'S-Breaker',
                                       'VLL-9 Laser'},
                        'secondary': {   'Cluster Bomb',
                                         'D-Missile',
                                         'EM Pulse',
                                         'Fang',
                                         'Fury',
                                         'Havoc',
                                         'Hornet',
                                         'Hornet#Weak',
                                         'Interceptor',
                                         'Interceptor#Weak',
                                         'MX-50',
                                         'Phoenix V'}},
    'PVB Amun': {   'primary': {   'Avenger',
                                   'Banshee',
                                   'Disruptor',
                                   'Flail',
                                   'Leech Cannon',
                                   'ML-16 Laser',
                                   'Prometheus',
                                   'Prometheus A',
                                   'Prometheus R',
                                   'S-Breaker',
                                   'VLL-9 Laser'},
                    'secondary': {   'Barracuda',
                                     'Cluster Bomb',
                                     'D-Missile',
                                     'Fang',
                                     'Fury',
                                     'Harbinger',
                                     'Havoc',
                                     'Hornet',
                                     'Hornet#Weak',
                                     'Interceptor',
                                     'Interceptor#Weak',
                                     'MX-50',
                                     'Phoenix V',
                                     'Stiletto',
                                     'Tsunami'}},
    'PVB Osiris': {   'primary': {   'Akheton SDG',
                                     'Avenger',
                                     'Banshee',
                                     'Disruptor',
                                     'Flail',
                                     'Leech Cannon',
                                     'ML-16 Laser',
                                     'Prometheus',
                                     'Prometheus A',
                                     'Prometheus R',
                                     'S-Breaker',
                                     'VLL-9 Laser'},
                      'secondary': {   'Barracuda',
                                       'Cluster Bomb',
                                       'D-Missile',
                                       'EM Pulse',
                                       'Fang',
                                       'Fury',
                                       'Havoc',
                                       'Interceptor',
                                       'Interceptor#Weak',
                                       'MX-50',
                                       'Phoenix V',
                                       'Stiletto',
                                       'Tsunami'}},
    'PVB Sekhmet': {   'primary': {   'Akheton SDG',
                                      'Avenger',
                                      'Disruptor',
                                      'Flail',
                                      'Leech Cannon',
                                      'ML-16 Laser',
                                      'Prometheus',
                                      'Prometheus A',
                                      'Prometheus R',
                                      'S-Breaker',
                                      'UD-1 Volz',
                                      'VLL-9 Laser'},
                       'secondary': {   'Barracuda',
                                        'Cluster Bomb',
                                        'EM Pulse',
                                        'Fang',
                                        'Fury',
                                        'Harbinger',
                                        'Havoc',
                                        'Hornet',
                                        'Hornet#Weak',
                                        'Interceptor',
                                        'Interceptor#Weak',
                                        'MX-50',
                                        'Phoenix V',
                                        'Stiletto',
                                        'Synaptic',
                                        'Tsunami'}},
    'PVDr Jackal': {'primary': {'Training'}, 'secondary': set()},
    'PVF Anubis': {   'primary': {   'Avenger',
                                     'Banshee',
                                     'Disruptor',
                                     'Flail',
                                     'Leech Cannon',
                                     'ML-16 Laser',
                                     'Prometheus',
                                     'Prometheus A',
                                     'Prometheus R',
                                     'S-Breaker',
                                     'VLL-9 Laser'},
                      'secondary': {   'D-Missile',
                                       'EM Pulse',
                                       'Fang',
                                       'Fury',
                                       'Hornet',
                                       'Hornet#Weak',
                                       'Interceptor',
                                       'Interceptor#Weak',
                                       'MX-50'}},
    'PVF Horus': {   'primary': {   'Avenger',
                                    'Banshee',
                                    'Flail',
                                    'Leech Cannon',
                                    'ML-16 Laser',
                                    'Prometheus',
                                    'Prometheus A',
                                    'Prometheus R',
                                    'S-Breaker',
                                    'VLL-9 Laser'},
                     'secondary': {   'EM Pulse',
                                      'Fang',
                                      'Fury',
                                      'Havoc',
                                      'Hornet',
                                      'Hornet#Weak',
                                      'Interceptor',
                                      'Interceptor#Weak',
                                      'MX-50',
                                      'Phoenix V'}},
    'PVF Seth': {   'primary': {   'Akheton SDG',
                                   'Avenger',
                                   'Banshee',
                                   'Disruptor',
                                   'Flail',
                                   'Leech Cannon',
                                   'ML-16 Laser',
                                   'Prometheus',
                                   'Prometheus A',
                                   'Prometheus R',
                                   'S-Breaker',
                                   'VLL-9 Laser'},
                    'secondary': {   'Cluster Bomb',
                                     'D-Missile',
                                     'EM Pulse',
                                     'Fang',
                                     'Fury',
                                     'Havoc',
                                     'Hornet',
                                     'Hornet#Weak',
                                     'Interceptor',
                                     'Interceptor#Weak',
                                     'MX-50',
                                     'Phoenix V',
                                     'Stiletto'}},
    'PVF Thoth': {   'primary': {   'Akheton SDG',
                                    'Avenger',
                                    'Disruptor',
                                    'Flail',
                                    'Leech Cannon',
                                    'ML-16 Laser',
                                    'Prometheus',
                                    'Prometheus A',
                                    'Prometheus R',
                                    'S-Breaker',
                                    'VLL-9 Laser'},
                     'secondary': {   'D-Missile',
                                      'EM Pulse',
                                      'Fang',
                                      'Fury',
                                      'Hornet',
                                      'Hornet#Weak',
                                      'Interceptor',
                                      'Interceptor#Weak',
                                      'MX-50'}},
    'PVF Ulysses': {   'primary': {   'Akheton SDG',
                                      'Avenger',
                                      'D-Advanced',
                                      'Disruptor',
                                      'Flail',
                                      'Leech Cannon',
                                      'ML-16 Laser',
                                      'Prometheus',
                                      'Prometheus A',
                                      'Prometheus R',
                                      'S-Breaker',
                                      'UD-1 Volz',
                                      'VLL-9 Laser'},
                       'secondary': {   'D-Missile',
                                        'EM Pulse',
                                        'Fang',
                                        'Fury',
                                        'Hornet',
                                        'Hornet#Weak',
                                        'Interceptor',
                                        'Interceptor#Weak',
                                        'MX-50'}},
    'SF Dragon#Terrans': {   'primary': {   'Avenger',
                                            'Banshee',
                                            'Disruptor',
                                            'Flail',
                                            'ML-16 Laser',
                                            'Prometheus',
                                            'Prometheus A',
                                            'Prometheus R',
                                            'UD-1 Volz',
                                            'VLL-9 Laser'},
                             'secondary': {   'D-Missile',
                                              'Fang',
                                              'Fury',
                                              'Hornet',
                                              'Hornet#Weak',
                                              'Interceptor',
                                              'Interceptor#Weak',
                                              'MX-50',
                                              'Phoenix V'}}}
