import os
import re

def parse_ship_tables(input_file, output_file):
    ship_capacities = {}
    current_ship = None
    
    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            
            # Match ship name
            name_match = re.match(r'^\$Name:\s*(.+)$', line)
            if name_match:
                current_ship = name_match.group(1).strip()
                continue
            
            # Match SBank Capacity
            cap_match = re.match(r'^\$SBank Capacity:\s*\(\s*(.+?)\s*\)$', line)
            if cap_match and current_ship:
                # SBank Capacity: ( 40, 40 ) -> [40, 40]
                caps_str = cap_match.group(1)
                # Split by comma or space
                caps = [int(x.strip()) for x in re.split(r'[, ]+', caps_str) if x.strip().isdigit()]
                ship_capacities[current_ship] = caps
    
    # Write to Markdown
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Secondary Bank Capacities\n\n")
        f.write("This file is automatically generated from ship_tables.txt by parse_tables.py. Do not edit manually.\n\n")
        for ship in sorted(ship_capacities.keys()):
            caps_str = ", ".join(str(c) for c in ship_capacities[ship])
            f.write(f"- {ship}: [{caps_str}]\n")
            
def parse_weapon_tables(input_file, output_file):
    weapon_sizes = {}
    current_weapon = None
    
    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            
            # Match weapon name
            name_match = re.match(r'^\$Name:\s*(.+)$', line)
            if name_match:
                current_weapon = name_match.group(1).strip()
                # Remove inline comments from weapon name if any (sometimes like Name: X  ; comment)
                if ';' in current_weapon:
                    current_weapon = current_weapon.split(';')[0].strip()
                continue
            
            # Match Cargo Size
            size_match = re.match(r'^\$Cargo Size:\s*([0-9.]+)', line)
            if size_match and current_weapon:
                size = float(size_match.group(1))
                weapon_sizes[current_weapon] = size
                
    # Write to Markdown
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Secondary Weapon Sizes\n\n")
        f.write("This file is automatically generated from weapon_tables.txt by parse_tables.py. Do not edit manually.\n\n")
        for weapon in sorted(weapon_sizes.keys()):
            f.write(f"- {weapon}: {weapon_sizes[weapon]}\n")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(base_dir)
    
    ship_file = os.path.join(parent_dir, 'ship_tables.txt')
    weapon_file = os.path.join(parent_dir, 'weapon_tables.txt')
    
    out_ship = os.path.join(parent_dir, 'secondary_bank_capacities.md')
    out_weapon = os.path.join(parent_dir, 'secondary_weapon_sizes.md')
    
    if os.path.exists(ship_file):
        parse_ship_tables(ship_file, out_ship)
    else:
        print("ship_tables.txt not found!")
        
    if os.path.exists(weapon_file):
        parse_weapon_tables(weapon_file, out_weapon)
    else:
        print("weapon_tables.txt not found!")
        
    print(f"Generated {out_ship}")
    print(f"Generated {out_weapon}")
