"""
parse_tables.py — FSO Ship/Weapon Table Parser

Parses raw FreeSpace Open table files to extract data needed by the
FSIF-to-FS2 converter's weapon supply validation logic.

Functions:
  parse_ship_tables(input_file, output_file)
      Reads ship_tables.txt and extracts the secondary-bank capacity
      (SBank Capacity) for every ship flagged as 'fighter' or 'bomber'.
      Writes results to secondary_bank_capacities.md.

  parse_weapon_tables(input_file, output_file)
      Reads weapon_tables.txt and extracts the cargo size (Cargo Size)
      for every weapon in the '#Secondary Weapons' section.
      Writes results to secondary_weapon_sizes.md.

Inputs  (expected in FSIF_to_FS2_Converter/):
  ship_tables.txt   — FSO ship tables file
  weapon_tables.txt — FSO weapon tables file

Outputs (written to FSIF_to_FS2_Converter/):
  secondary_bank_capacities.md
  secondary_weapon_sizes.md

Usage:
  python tools/parse_tables.py
  (Run from the FSIF_to_FS2_Converter/ directory or its parent.)
"""

import os
import re

def parse_ship_tables(input_file, output_file):
    ship_capacities = {}
    current_ship = None
    pending_capacity = None  # buffered until $Flags: is parsed
    
    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            
            # Match ship name — reset state for the new ship
            name_match = re.match(r'^\$Name:\s*(.+)$', line)
            if name_match:
                current_ship = name_match.group(1).strip()
                pending_capacity = None  # reset buffer for new ship
                continue
            
            # Match SBank Capacity — buffer it; only commit once flags confirm fighter/bomber
            cap_match = re.match(r'^\$SBank Capacity:\s*\(\s*(.+?)\s*\)$', line)
            if cap_match and current_ship:
                # SBank Capacity: ( 40, 40 ) -> [40, 40]
                caps_str = cap_match.group(1)
                # Split by comma or space
                caps = [int(x.strip()) for x in re.split(r'[, ]+', caps_str) if x.strip().isdigit()]
                pending_capacity = caps
                continue
            
            # Match Flags — only commit the buffered capacity if ship is a fighter or bomber
            flags_match = re.match(r'^\$Flags:\s*\((.+?)\)$', line)
            if flags_match and current_ship and pending_capacity is not None:
                flags_str = flags_match.group(1)
                # Extract individual flag tokens (quoted strings)
                flags = set(re.findall(r'"([^"]+)"', flags_str))
                if 'fighter' in flags or 'bomber' in flags:
                    ship_capacities[current_ship] = pending_capacity
                pending_capacity = None  # clear buffer regardless
                continue
    
    # Write to Markdown
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Secondary Bank Capacities\n\n")
        f.write("This file is automatically generated from ship_tables.txt by parse_tables.py. Do not edit manually.\n\n")
        f.write("Only fighters and bombers are included (ships with 'fighter' or 'bomber' flag).\n\n")
        for ship in sorted(ship_capacities.keys()):
            caps_str = ", ".join(str(c) for c in ship_capacities[ship])
            f.write(f"- {ship}: [{caps_str}]\n")
            
def parse_weapon_tables(input_file, output_file):
    weapon_sizes = {}
    current_weapon = None
    in_secondary_section = False  # only parse weapons in the #Secondary Weapons section
    
    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            stripped = line.strip()
            
            # Track section headers to know when we're in #Secondary Weapons
            if stripped == '#Secondary Weapons':
                in_secondary_section = True
                current_weapon = None
                continue
            
            # Any other section header (#Primary Weapons, #Beam Weapons, #Countermeasures, #End, etc.)
            # ends the secondary section
            if stripped.startswith('#'):
                in_secondary_section = False
                current_weapon = None
                continue
            
            # Only process entries inside the secondary weapons section
            if not in_secondary_section:
                continue
            
            # Match weapon name
            name_match = re.match(r'^\$Name:\s*(.+)$', stripped)
            if name_match:
                current_weapon = name_match.group(1).strip()
                # Remove inline comments from weapon name if any (sometimes like Name: X  ; comment)
                if ';' in current_weapon:
                    current_weapon = current_weapon.split(';')[0].strip()
                continue
            
            # Match Cargo Size
            size_match = re.match(r'^\$Cargo Size:\s*([0-9.]+)', stripped)
            if size_match and current_weapon:
                size = float(size_match.group(1))
                weapon_sizes[current_weapon] = size
                
    # Write to Markdown
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Secondary Weapon Sizes\n\n")
        f.write("This file is automatically generated from weapon_tables.txt by parse_tables.py. Do not edit manually.\n\n")
        f.write("Only secondary weapons (missiles) are included.\n\n")
        for weapon in sorted(weapon_sizes.keys()):
            f.write(f"- {weapon}: {weapon_sizes[weapon]}\n")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.dirname(base_dir)
    
    ship_file = os.path.join(parent_dir, 'ship_tables.txt')
    weapon_file = os.path.join(parent_dir, 'weapon_tables.txt')
    
    out_ship = os.path.join(parent_dir, 'secondary_bank_capacities.md')
    out_weapon = os.path.join(parent_dir, 'secondary_weapon_sizes.md')
    
    if os.path.exists(ship_file):
        parse_ship_tables(ship_file, out_ship)
    else:
        print("ship_tables.txt not found!")
        
    if os.path.exists(weapon_file):
        parse_weapon_tables(weapon_file, out_weapon)
    else:
        print("weapon_tables.txt not found!")
        
    print(f"Generated {out_ship}")
    print(f"Generated {out_weapon}")
